server:
  port: 8083  # API: 8080, Streamer: 8082, Batch: 8083

spring:
  application:
    name: commerce-batch

  profiles:
    active: local

  config:
    import:
      - jpa.yml
      - redis.yml

  # Spring Batch
  batch:
    job:
      enabled: false  # 애플리케이션 시작 시 자동 실행 방지
    jdbc:
      initialize-schema: always  # Spring Batch 메타 테이블 자동 생성

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: test
  batch:
    job:
      enabled: false